routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Route::get('/hello', function () {
//     //return view('welcome');
//     return ( 
//     "<div class=header>
//         <h1>How you doing!</h1>
//     </div>");
// });

// Route::get('/users/{id}/{name}', function($id, $name){
//     return  "User: ".$id. "and name: ". $name;
// });

Route::get('/', 'PagesController@index');
Route::get('/about', 'PagesController@about');
Route::get('/services', 'PagesController@services');
Route::resource("posts", "PostsController");
Route::resource("customers", "CustomersController");
Route::resource("products", "ProductsController");
Route::resource("categories", "CategoryController");
//Route::resource("users", "UsersController");


Route::get('/shopping-cart', [
    'uses' => 'CartController@getShoppingCart',
	'as' => 'product.getShoppingCart'
]);

Route::get('/checkout', [
    'uses' => 'CartController@getCheckout',
	'as' => 'product.getCheckout'
]);

Route::post('/checkout', [
    'uses' => 'CartController@postCheckout',
	'as' => 'product.postCheckout'
]);


Route::get('/removeFromCart/{id}', [
	'uses' => 'CartController@removeFromCart',
	'as' => 'product.removeFromCart'	
]);


Route::get('/addToCart/{id}', [
	'uses' => 'CartController@addToCart',
	'as' => 'product.addToCart'
]);

Route::get('/updateQuantity/{item}/{action}', [
    'uses' => 'CartController@updateQuantity',
	'as' => 'product.updateQuantity'
]);

Route::group(['prefix'=> 'user'], function(){
    Route::group(['middleware'=> 'guest'], function(){
        // Signing up
        Route::get('/signup', [
            'uses'=> 'UserController@getSignup',
            'as'=> 'user.signup'
        ]);

        Route::post('/signup', [
            'uses'=> 'UserController@postSignup',
            'as'=> 'user.signup'
        ]);
        
        // Signin in
        Route::get('/signin', [
            'uses'=> 'UserController@getSignin',
            'as'=> 'user.signin'
        ]);
        
        Route::post('/signin', [
            'uses'=> 'UserController@postSignin',
            'as'=> 'user.signin'
        ]);
    });

    Route::group(['middleware'=> 'auth'], function(){
        // Profile
        Route::get('/profile', [
            'uses'=> 'UserController@getProfile',
            'as'=> 'user.profile'
        ]);
        
        //Logout
        Route::get('/logout', [
            'uses'=> 'UserController@getLogout',
            'as'=> 'user.logout'
        ]);

        Route::get('/profile/{id}', [
            'uses'=> 'CartController@cancelOrder',
            'as'=> 'product.cancelOrder'
        ]);
    });
    
});

resources/views/shop/checkout.blade.php
@extends('layouts.app')

@section('content')

<!--Main layout-->
<main class="">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="m-4 h3 text-center  bg-light  text-center ">Checkout</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" action="{{route('product.postCheckout')}}"  class="card-body">
                
              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">
                  <!--firstName-->
                  <div class="md-form ">
                    <input required type="text" id="firstName" class="form-control">
                    <label for="firstName" class="">First name</label>
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--lastName-->
                  <div class="md-form">
                    <input required name="name" type="text" id="lastName" class="form-control">
                    <label  for="lastName" class="">Last name</label>
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              
              <!--email-->
              <div class="md-form mb-3">
                <input required name="email" type="text" id="email" class="form-control" placeholder="youremail@example.com">
                <label for="email" class="">Email</label>
              </div>

              <!--address-->
              <div class="md-form mb-3">
                <input required name="address" type="text" id="address" class="form-control" placeholder="1234 Main St">
                <label for="address" class="">Address</label>
              </div>


              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  <select class="custom-select d-block w-100" id="country" required>
                    <option value="">Choose...</option>
                    <option>Netherlands</option>
                  </select>
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="state">State</label>
                  <select class="custom-select d-block w-100" id="state" required>
                    <option value="">Choose...</option>
                    <option>Rotterdam</option>
                    <option>Dordrecht</option>
                  </select>
                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  <input type="text" class="form-control" id="zip" placeholder="" required>
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="same-address">
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="save-info">
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

             
              <hr class="mb-4">
              {{csrf_field() }}
              <button class="btn btn-info btn-lg btn-block" type="submit">Finish order</button>


              

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{$totalQuantity}}</span>
          </h4>


          @if(Session::has('cart'))
          <!-- Cart -->
          
            
            @foreach($products as $product)
        
            <ul class="list-group mb-3 z-depth-1">
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                  <div>
                    <h6 class="my-0">{{$product['item']['name']}}  <span class="badge badge-secondary badge-pill">{{$product['qty']}}</span> </h6>
                    <small class="text-muted">{{$product['item']['description']}}</small>
                  </div>
                  <span class="text-muted">{{$product['item']['price']}}</span>
                </li>
           @endforeach
           
            {{-- <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li> --}}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total</span>
              <strong>€ {{$totalPrice}}</strong>
            </li>
          </ul>
          @endif
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

@endsection

resources/views/shop/shopping-cart.blade.php
@extends('layouts.app')

@section('content')
<div class="container mb-4">
    @if(Session::has('cart'))
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"> </th>
                            <th scope="col">Product</th>
                            <th scope="col">Available</th>
                            <th scope="col" class="text-center">Quantity</th>
                            <th scope="col" class="text-right">Price</th>
                            <th scope="col" class="text-right">Empty</th>
                            
                             
                        </tr>
                    </thead>
                    <tbody>
                        {{-- {{dd($products)}} --}}
                        @foreach($products as $product)
                        {{-- {{dd($product)}} --}}
                        <tr>
                            <td><img height="50" src="../images/{{$product['item']['image']}}" /> </td>
                            <td>{{$product['item']['name']}}</td>
                            <td>In stock</td>
                            <td style="text-align: center">{{$product['qty']}}</td>
                            <td class="text-right">{{$product['price']}}</td>
                            <td class="text-right">
                                <a href="{{route('product.updateQuantity', ['item' => $product['item'], 'add'])}}" class="btn btn-sm btn-success "><i class="fa fa-plus"></i></a>
                                <a href="{{route('product.updateQuantity', ['item' => $product['item'], 'minus'])}}" class="btn btn-sm btn-warning "><i class="fa fa-minus"></i></a>
                                <a href="{{route('product.removeFromCart', ['id' => $product['item']])}}" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> </a> 
                            </td>
                        </tr>
                       @endforeach
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>Sub-Total</td>
                            <td class="text-right">€ 0</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>Shipping</td>
                            <td class="text-right">€ 0</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Total</strong></td>
                            <td class="text-right"><strong>€ {{$totalPrice}}</strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col mb-2">
            <div class="row">
                <div class="col-sm-12  col-md-6 text-right">
                    <a href="/categories" class="btn btn-lg btn-block btn-warning text-uppercase">Continue Shopping</a>
                </div>
                <div class="col-sm-12 col-md-6 text-right">
                    <a href="{{route('product.getCheckout')}}" class="btn btn-lg btn-block btn-success text-uppercase">Checkout</a>
                </div>
            </div>
        </div>
        @else
       
       
        <div class="alert alert-danger m-3 p">
            <h2 style="text-align: center; margin: 20px;">No Products found in Shopping cart</h2>
        </div>
        <script>window.location = "{{ route('categories.index') }}";</script>
        @endif
        
    </div>
</div>

@endsection